patterns:
  - comment: 'config - oneline'
    match: !regex |-
      (@config)\s+
      ([\w\d_]+)\s+
      (.*)
    captures:
      '1':
        name: keyword.control.pintora
      '2':
        name: support.type.property-name.pintora
      '3':
        name: string.value

  - comment: 'config - block'
    begin: !regex |-
      (@config)\s+
      (\{)
    beginCaptures:
      '1':
        name: keyword.control.pintora
      '2':
        name: punctuation.bracket.open.pintora
    end: '(\})'
    endCaptures:
      '1':
        name: keyword.control.pintora
    patterns:
      - include: '#config__part'
