patterns:
  - comment: '@config'
    begin: !regex |-
      (@config)
      (\()
    beginCaptures:
      '1':
        name: keyword.control.pintora
      '2':
        name: support.type.property-name.pintora
      '3':
        name: string.value
    end: '\)'
    endCaptures:
      '1':
        name: keyword.control.pintora
    patterns:
      - include: "source.json"

  - comment: '@param - oneline'
    match: !regex |-
      (@param)\s+
      ([\w\d_]+)\s+
      (.*)
    captures:
      '1':
        name: keyword.control.pintora
      '2':
        name: support.type.property-name.pintora
      '3':
        name: string.value

  - comment: '@param - block'
    begin: !regex |-
      (@param)\s+
      (\{)
    beginCaptures:
      '1':
        name: keyword.control.pintora
      '2':
        name: punctuation.bracket.open.pintora
    end: '(\})'
    endCaptures:
      '1':
        name: keyword.control.pintora
    patterns:
      - include: '#config__part'
